
eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-api
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/student/**
        - id: school-api
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/school/**
